### ISSUE TITLE
Hello author, I am a sophomore student and I am honored to have read your article on 'Non-line-of-sight transient rendering.

### ISSUE THREAD

**Issue by min-yang5** [diegoroyo/mitsuba2#3]
"I didn't understand how to deploy this project. Can you provide guidance on that?". The mitsuba2-transient-nlos and mitsuba2, what are the differences between them?"

**Comment by diegoroyo** [comment]
Thanks for your interest on the project. `mitsuba2-transient-nlos` is basically `mitsuba2` with some extra code that adds functionality to simulate time-resolved renders which work well for NLOS capture setups.

To deploy this project, you will need to compile the code. You can follow the same instructions as for `mitsuba2`: https://mitsuba2.readthedocs.io/en/latest/src/getting_started/compiling.html. We have tested `mitsuba2-transient-nlos` in Linux.

Then, to execute `mitsuba2-transient-nlos`, you have two options:
* Create an XML scene description file and use it within the program: https://mitsuba2.readthedocs.io/en/latest/src/getting_started/file_format.html (then execute it as `./mitsuba <path_to_xml>`)
* Use our Python library that helps you to create XML files for NLOS scenes: https://github.com/diegoroyo/tal . Check the `tal render` command in the README.

**Comment by min-yang5** [comment]
Hello! It seems like you've set up Mitsuba2 Transient NLOS and the tal library successfully. However, when you execute the rendering command "tal render nlos-z," you encounter an error. I hope the author can provide some advice.

(daopython) dao@dao-virtual-machine:~/anaconda3/envs/daopython/bin$ tal render /home/dao/tal/examples/render-reconstruct/nlos-z
Traceback (most recent call last):
  File "/home/dao/anaconda3/envs/daopython/bin/tal", line 8, in <module>
    sys.exit(main())
  File "/home/dao/anaconda3/envs/daopython/lib/python3.10/site-packages/tal/__main__.py", line 133, in main
    render_nlos_scene(config_file, args)
  File "/home/dao/anaconda3/envs/daopython/lib/python3.10/site-packages/tal/render/__init__.py", line 30, in render_nlos_scene
    render.render_nlos_scene(config_path, args)
  File "/home/dao/anaconda3/envs/daopython/lib/python3.10/site-packages/tal/render/render.py", line 56, in render_nlos_scene
    mitsuba_backend.set_variant(scene_config['mitsuba_variant'])
  File "/home/dao/anaconda3/envs/daopython/lib/python3.10/site-packages/tal/render/mitsuba2_transient_nlos.py", line 55, in set_variant
    raise AssertionError(
AssertionError: Variant llvm_rgb is not supported. It must start with "scalar_"

**Comment by diegoroyo** [comment]
You should look in your `nlos-z/nlos-z.yaml` file. Search for this line:

`mitsuba_variant: llvm_rgb`

You should change it to:

`mitsuba_variant: scalar_rgb`

Hope it helps. If you have any further questions feel free to ask.

**Comment by min-yang5** [comment]
"Thank you for your response. I have some questions I'd like to ask the author。

I downloaded the test file you provided (testz.yaml) and executed it using the command (tal render /home/dao/tal-example1/testz.yaml). It generated the scene files (nlos_scene.xml, steady_scene.xml), but at the same time, an error occurred. Here is the specific error message:"
RuntimeError: ​[FileStream] "/home/dao/tal-example1/20231221-105905/partial/testz_back_view.exr": I/O error while attempting to open file: No such file or directory

1，Why wasn't an HDF5 file generated? How can I obtain it?
2，When I use the Mitsuba command (mitsuba steady_scene.xml), it generates an EXR file, but when I try to convert it to a JPG file, there is no image？
3，What is the estimated rendering time for completing an NLOS scene?


Certainly, please go ahead and provide the detailed error message in the form of an image. 

![屏幕截图 2023-12-21 110258](https://github.com/diegoroyo/mitsuba2-transient-nlos/assets/127475936/a4f9c1dc-8c27-487e-b86e-719e61238696)
![屏幕截图 2023-12-21 152218](https://github.com/diegoroyo/mitsuba2-transient-nlos/assets/127475936/4c86d131-75cd-4cef-8c01-87b4f64a948e)

**Comment by diegoroyo** [comment]
The problem is that tal executed mitsuba, but mitsuba returned an error code 255. The files in the `logs` folder should contain more information of what the error 255 is about.

Note that the yaml file you downloaded probably needs a obj file to load. You can check out one example here: https://github.com/diegoroyo/tal/blob/67462fd079ef2fcfdc6c4d951dd3f55f79648ce4/examples/render-reconstruct/nlos-z/nlos-z.yaml#L106. Read the whole file for more information.

Have you downloaded that Z.obj file? If you run tal like `tal render testz.yaml`, you should put the Z.obj file in the same folder as `testz.yaml`. You can download Z.obj here: https://nas-graphics.unizar.es/s/mitsuba2-transient-nlos-example

If the errors persist, please upload your `yaml` file and the `logs` folder for next time.

**Comment by min-yang5** [comment]
Hello, I've tried again a few times and still encountered errors. I've uploaded the log and YAML files to my project. Could you please check all the files?（https://github.com/min-yang5/tal-render）

<img width="1122" alt="屏幕截图 2023-12-23 165603" src="https://github.com/diegoroyo/mitsuba2-transient-nlos/assets/127475936/65912601-9ed8-42db-8037-8e3d43fd8048">

The content displayed in the log is as follows.
terminating with uncaught exception of type std::runtime_error: ​[Profiler] profiler_start(): failure in setitimer(): Invalid argument


Looking forward to your response again.
